### ISSUE TITLE
Latest image fails to start

### ISSUE THREAD

**Issue by basilnsage** [Unleash/unleash-docker#50]
Hiya,

The latest image release (as of time of writing) `sha256:37e41fde6c33bfe7df3f409631d5a876c3046f852e51eb797025f746040e207f` fails to start due to a Node issue. It looks like this was introduced with `unleash-server` was upgraded to 4.1.1.

Repro steps:
1. Download the image
```
docker pull unleashorg/unleash-server@sha256:37e41fde6c33bfe7df3f409631d5a876c3046f852e51eb797025f746040e207f

docker.io/unleashorg/unleash-server@sha256:37e41fde6c33bfe7df3f409631d5a876c3046f852e51eb797025f746040e207f: Pulling from unleashorg/unleash-server
Digest: sha256:37e41fde6c33bfe7df3f409631d5a876c3046f852e51eb797025f746040e207f
Status: Image is up to date for unleashorg/unleash-server@sha256:37e41fde6c33bfe7df3f409631d5a876c3046f852e51eb797025f746040e207f
docker.io/unleashorg/unleash-server@sha256:37e41fde6c33bfe7df3f409631d5a876c3046f852e51eb797025f746040e207f
```
2. Run
```
docker run unleashorg/unleash-server@sha256:37e41fde6c33bfe7df3f409631d5a876c3046f852e51eb797025f746040e207f

/unleash/node_modules/unleash-server/dist/lib/routes/admin-api/feature.js:69
        const strategies = globalEnv?.strategies || [];
                                     ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/unleash/node_modules/unleash-server/dist/lib/routes/admin-api/index.js:8:35)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

Is it possible for someone to take a look please?

Thanks much.

**Comment by ivarconr** [comment]
Thanks for reporting. I see there is a bug in our release script where default node version has been set to node 12. Unleash dropped support for node 12 in V4.

**Comment by ivarconr** [comment]
should be fixrd for latest and all 4.1 tags.

**Comment by basilnsage** [comment]
Thanks much!
