### ISSUE TITLE
In v.4.6.1, failed to start by docker-compose 

### ISSUE THREAD

**Issue by yuike** [Unleash/unleash-docker#62]
Hi.

It worked fine with docker, but failed with docker-compose.

```
web_1  | internal/modules/cjs/loader.js:905
web_1  |   throw err;
web_1  |   ^
web_1  |
web_1  | Error: Cannot find module '/unleash/npm'
web_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
web_1  |     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
web_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
web_1  |     at internal/main/run_main_module.js:17:47 {
web_1  |   code: 'MODULE_NOT_FOUND',
web_1  |   requireStack: []
web_1  | }
unleash-docker_web_1 exited with code 1
```

It seems that the following commit (`91cb2f5755244bc2b011c03515aea878ed6fcfba `) line is affected.

```dockerfile
RUN rm -rf /usr/local/lib/node_modules/npm/
```

If I removed this line, it will work with docker-compose.
Can you fix this problem?

**Comment by ivarconr** [comment]
thanks @yuike, we removed npm in v4.6, but forgot to update the docker-compose example. 

Fixed direly on main!
